Implement MODE

diff --git a/main b/main
--- a/main
+++ b/main
@@ -3,46 +3,81 @@
 set -eu
 
 main() {
-  pr_list_json=$(
-    # Get merge commits
-    # git --no-pager log --oneline --reverse --merges origin/"$BASE"..origin/"$HEAD" |
-    git --no-pager log --oneline --reverse origin/"$BASE"..origin/"$HEAD" |
-
-    # Extract merge commit hashes
-    awk '{ print $1 }' |
-
-    # Retrieve a JSON from an API
-    #
-    #   Memo:
-    #     Call as many APIs as PRs
-    #     I'm not sure how to put all calls together
-    xargs -I {} gh api "https://api.github.com/repos/$REPOSITORY/commits/{}/pulls"
-  )
-
-  # WIP: Extract commits not associated with PRs (for squash commits)
-  # commits_associated_with_prs=$(
-  #   echo "$pr_list_json" |
-  #   jq -r .[].number |
-  #   xargs -I {} gh api "https://api.github.com/repos/$REPOSITORY/pulls/{}/commits" --jq .[].sha
-  # )
-
-  # no_merge_commits=$(
-  #   git --no-pager log --oneline --reverse --no-merges --no-abbrev-commit origin/"$BASE"..origin/"$HEAD" |
-  #   awk '{ print $1 }'
-  # )
-
-  # commits_not_associated_with_prs=$(
-  #   echo "$no_merge_commits" |
-  #   grep -v "$commits_associated_with_prs"
-  # )
-
-  # git --no-pager log --format="%H %s %an" --reverse origin/"$HEAD" | grep "$commits_not_associated_with_prs" | sed -e 's/^[0-9a-f]* //g'
-  # END WIP
-
+  prs=$(pr_list_json)
   comment
-
   # It should be performed at the end because it will exit if posting a message to Slack fails
   post_to_slack
+}
+
+# It should be performed only once because it calls GitHub API many times
+pr_list_json() {
+  case $MODE in
+    merge)
+      result=$(
+        # Get merge commits
+        git --no-pager log --oneline --reverse --merges origin/"$BASE"..origin/"$HEAD" |
+
+        # Extract merge commit hashes
+        awk '{ print $1 }' |
+
+        # Retrieve a JSON from an API
+        #
+        #   Memo:
+        #     Call as many APIs as PRs
+        #     I'm not sure how to put all calls together
+        xargs -I {} gh api "https://api.github.com/repos/$REPOSITORY/commits/{}/pulls"
+      )
+
+      ;;
+    squash)
+      result=$(
+        git --no-pager log --oneline --reverse origin/"$BASE"..origin/"$HEAD" |
+        awk '{ print $1 }' |
+        xargs -I {} gh api "https://api.github.com/repos/$REPOSITORY/commits/{}/pulls"
+      )
+
+      ;;
+    rebase)
+      merged_prs=$(
+        git --no-pager log --oneline --reverse --merges origin/"$BASE"..origin/"$HEAD" |
+        awk '{ print $1 }' |
+        xargs -I {} gh api "https://api.github.com/repos/$REPOSITORY/commits/{}/pulls"
+      )
+
+      commits_associated_with_merged_prs=$(
+        echo "$merged_prs" |
+        jq -r .[].number |
+        xargs -I {} gh api "https://api.github.com/repos/$REPOSITORY/pulls/{}/commits" --jq .[].sha
+      )
+
+      no_merge_commits=$(
+        git --no-pager log --oneline --reverse --no-merges --no-abbrev-commit origin/"$BASE"..origin/"$HEAD" |
+        awk '{ print $1 }'
+      )
+
+      # (no merge commits) - (commits associated with merged PRs) =
+      # (squash commits & rebase commits & commits not associated with any PRs)
+      squash_and_rebase_and_orphan_commits=$(
+        echo "$no_merge_commits" |
+        grep -v "$commits_associated_with_merged_prs" |
+        xargs -I {} gh api "https://api.github.com/repos/$REPOSITORY/commits/{}/pulls"
+      )
+
+      # Combine (merged PRs) & (squash commits & rebase commits & commits not associated with any PRs)
+      result=$(
+        printf "%s\n%s" "$merged_prs" "$squash_and_rebase_and_orphan_commits" |
+        jq -s 'add'
+      )
+
+      ;;
+    *)
+      echo "Error: Unrecognized mode \"$MODE\" is detected" >&2
+      exit 1
+
+      ;;
+  esac
+
+  echo "$result"
 }
 
 comment() {
@@ -97,10 +132,10 @@ pr_numbers() {
 
   case $type in
     github)
-      echo "$pr_list_json" | jq -r .[].number | sed -e 's/^/#/g'
+      echo "$prs" | jq -r .[].number | sed -e 's/^/#/g'
       ;;
     slack)
-      echo "$pr_list_json" | jq -r .[].number | xargs -I {} echo "<https://github.com/$REPOSITORY/pull/{}|#{}>"
+      echo "$prs" | jq -r .[].number | xargs -I {} echo "<https://github.com/$REPOSITORY/pull/{}|#{}>"
       ;;
   esac
 }
@@ -109,7 +144,7 @@ titles() {
   type=$1
 
   if $TITLE || [ "$type" = "slack" ]; then
-    echo "$pr_list_json" | jq -r .[].title
+    echo "$prs" | jq -r .[].title
   else
     echo ""
   fi
@@ -125,10 +160,10 @@ authors() {
 
   case $type in
     github)
-     echo "$pr_list_json" | jq -r .[].user.login | sed -e 's/^/@/g'
+     echo "$prs" | jq -r .[].user.login | sed -e 's/^/@/g'
       ;;
     slack)
-     echo "$pr_list_json" | jq -r .[].user.login | sed -e 's/^/by `@/g' | sed -e 's/$/`/g'
+     echo "$prs" | jq -r .[].user.login | sed -e 's/^/by `@/g' | sed -e 's/$/`/g'
       ;;
   esac
 }
@@ -136,6 +171,8 @@ authors() {
 lists() {
   type=$1
 
+  # Slack API does not support bulleted lists
+  #   https://zapier.com/help/doc/tips-formatting-your-slack-messages
   if [ "$type" = "slack" ]; then
     echo "• "
   elif $CHECKBOX; then
