Exit if posting fails

diff --git a/main b/main
--- a/main
+++ b/main
@@ -19,6 +19,8 @@ main() {
   )
 
   comment
+
+  # It should be performed at the end because it will exit if posting a message to Slack fails
   post_to_slack
 }
 
@@ -58,6 +60,7 @@ fi
 
   if ! $ok; then
     echo "Error: Failed to post a message to Slack." >&2
+    exit 1
   fi
 }
 
